cmdb/urls.py
# coding=utf-8
#

from django.conf.urls import url

from host import *  # host, a10
# from app import *  # app,
# from balance import *
# from views import *  # es, user, 证书
# from zabbix import zabbix_tomcat_app
# from dk import *
# from appsh import *


urlpatterns = [

    url(r'^host/add', host_add, name="host_add"),
    url(r'^host/del', host_del, name="host_del"),
    url(r'^host/alldel', host_alldel, name="host_alldel"),
    url(r'^host/(?P<id>\d+)/$', host_edit, name="host_edit"),
    # url(r'^group',  Group.as_view(), name="group"),
    url(r'^host', host, name="host"),
    # url(r'^(host)',  asset, name="host"),

    url(r'^webssh', WebSSH.as_view(), name="webssh"),
    url(r'^cmdrun', CmdRun.as_view(), name="cmdrun"),


]

webssh/urls.py
# coding=utf-8
"""sdj URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from views import index
# from django.conf import settings
# from django.contrib.auth.views import login,logout

from django.views.generic.base import RedirectView

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # url(r'^admin/login', RedirectView.as_view(pattern_name="login"), ),  # 增加了otp验证
    # url(r'^admin/password_change', RedirectView.as_view(pattern_name="password_change"), ),  # 增加了密码过期验证
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^cmdb/', include('cmdb.urls', namespace="cmdb", app_name='cmdb')),

    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicon.ico', permanent=True), ),
    url(r'^$', index),

]


urlpatterns += staticfiles_urlpatterns()

import mimetypes
if '.svg' not in mimetypes.types_map:
    # CentOS7默认安装的python2.7.5版本偏旧，mime不含svg，导致svg图片不显示
    # 使用nginx，mime支持svg
    mimetypes.types_map['.svg'] = 'image/svg+xml'

cmdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
# from django.utils.timezone import now, localdate
from datetime import datetime, timedelta

from django.contrib.auth.models import User, Group
import traceback
from Crypto.Cipher import AES
import base64
import paramiko


# from django.db.models.options import Options
# old_contribute_to_class = Options.contribute_to_class


# def new_contribute_to_class(instance, cls, name):
#     # 设置verbose_name_plural为verbose_name
#     old_contribute_to_class(instance, cls, name)
#     instance.verbose_name_plural = instance.verbose_name
# models.options.Options.contribute_to_class = new_contribute_to_class


class HostGroup(models.Model):
    name = models.CharField(u"组名/区域", max_length=30, unique=True)
    ip = models.CharField(u"IP匹配", help_text='IP开头字符，比如Core组IP为10.2.4.开头。用于客户端脚本添加新主机时自动设置组，不支持通配符', max_length=20, default='', blank=True)
    desc = models.CharField(u"描述", max_length=100, null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = '主机分组'

    def __unicode__(self):
        return self.name

    @staticmethod
    def get_group(ip):
        # 客户端脚本自动添加主机时，自动设置主机所属组(安全区域)

        groups = HostGroup.objects.exclude(ip='').order_by('-ip')
        group_id = 0
        for group in groups:
            if ip.startswith(group.ip):
                group_id = group.id
                break
        return group_id


def get_AES(password, encode=1):
    # 密码加密

    KEY = '1234567890123456'
    BLOCK_SIZE = 16  # AES.block_size
    PADDING = chr(20)  # 'ý' #未满16*n时，补齐字符chr(253)

    pad = lambda s: s + (BLOCK_SIZE - len(s) % BLOCK_SIZE) * PADDING
    EncodeAES = lambda c, s: base64.b64encode(c.encrypt(pad(s)))
    DecodeAES = lambda c, e: c.decrypt(base64.b64decode(e)).rstrip(PADDING)
    cipher = AES.new(KEY)
    if encode:
        # 密码加密，用于内部保存
        # try:
        #     decoded = DecodeAES(cipher, password)
        # return  password #未修改密码直接提交，原字符已为密文，无需再次加密
        # except:
        #     pass
        return EncodeAES(cipher, password)  # 修改了密码，重新加密为密文
    else:
        # 密码解密，用于外部提取
        try:
            return DecodeAES(cipher, password)
        except:
            print 'Error: AES密码解密失败！！'
            return ''


class SshUser(models.Model):
    # 各服务器SSH登陆用户
    name = models.CharField(u"名称", max_length=50, default='', help_text='标识名称，当不同服务器使用相同的SSH账号名，但密码不同时，此项名称可进行区分。')
    username = models.CharField(u"SSH账号", max_length=50, default='', )
    password = models.CharField(u"密码", max_length=50, default='', null=True, blank=True, help_text='若不想修改原密码，不用设置此项')
    changetime = models.DateTimeField('最后修改', auto_now=True, blank=True, null=True)
    text = models.TextField(u"备注信息", default='', null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = '主机SSH用户'
        unique_together = [('name', 'username'), ]

    def __unicode__(self):
        return '%s - %s' % (self.name, self.username)

    def save(self, *args, **kwargs):

        if self.password:
            password_aes = get_AES(password=self.password)  # AES加密
            self.password = password_aes
        elif self.id:
            del self.password  # 防止不修改密码时，提交的空密码覆盖原有数据
        # import ipdb;ipdb.set_trace()
        super(self.__class__, self).save(*args, **kwargs)  # Call the "real" save() method.


class Host(models.Model):
    # 虚拟机、物理机 等设备
    ASSET_STATUS = (
        (1, u"在用"),
        (2, u"备用"),
        (3, u"故障"),
        (4, u"下线"),
        (6, u"其它"),
    )

    ASSET_TYPE = (
        (1, u"物理机"),
        (2, u"虚拟机"),
        (3, u"容器"),
        (4, u"H3C交换机"),
        (6, u"其它")
    )

    name = models.CharField(max_length=100, verbose_name=u"标识名称", default='', help_text='用于人工辨别，自动脚本默认设置为主机名，可改为其它便于人员识别的名称')
    hostname = models.CharField(max_length=50, verbose_name=u"主机名/计算机名", unique=True, help_text='关键字段，请谨慎修改')  # 服务器数据以计算机名为锚，以验证身份不重复添加数据
    ip = models.GenericIPAddressField(u"管理IP", max_length=15, help_text='若有多个IP且主机名无指定解析则默认为0.0.0.0，请在客户端/etc/hosts中设置其主机名对应IP解析')
    port = models.IntegerField(verbose_name='ssh端口', null=True, blank=True, default=22)
    other_ip = models.CharField(u"其它IP", max_length=100, null=True, blank=True)
    group = models.ForeignKey(HostGroup, verbose_name=u"组/安全区域", default=1, on_delete=models.SET_NULL, null=True, blank=True)
    # asset_no = models.CharField(u"资产编号", max_length=50, null=True, blank=True)
    # domain = models.CharField(u"安全区域", max_length=20, null=True, blank=True)
    status = models.SmallIntegerField(u"设备状态", choices=ASSET_STATUS, default=1, null=True, blank=True)
    asset_type = models.SmallIntegerField(u"设备类型", choices=ASSET_TYPE, default=1, null=True, blank=True)
    # 注意，django 1.11对postgresql 8.*低版本支持不好，ForeignKey字段有修改就会SQL报错 array_agg(attname ORDER BY rnum)
    machine = models.ForeignKey('self', verbose_name=u"所属物理机", limit_choices_to={'asset_type': 1},
                                on_delete=models.SET_NULL, null=True, blank=True, help_text='设备类型为虚拟机/容器时，设置所在物理机')
    os = models.CharField(u"操作系统", max_length=100, default='', null=True, blank=True)
    # vendor = models.CharField(u"设备厂商", max_length=50, null=True, blank=True)
    cpu_model = models.CharField(u"CPU型号", max_length=100, default='', null=True, blank=True)
    cpu_num = models.CharField(u"CPU数量", max_length=100, default='', null=True, blank=True, help_text='物理核个数, 逻辑核个数，(intel高端CPU带超线程技术)')
    memory = models.CharField(u"内存大小", max_length=30, default='', null=True, blank=True)
    disk = models.CharField(u"硬盘信息", max_length=255, default='', null=True, blank=True)
    vendor = models.CharField(u"供应商", max_length=150, default='', null=True, blank=True)
    sn = models.CharField(u"主机序列号", max_length=150, default='', null=True, blank=True)
    ports = models.TextField(u"监听端口", default='', null=True, blank=True, help_text='主机上处于监听状态的TCP和UDP端口')

    createtime = models.DateTimeField('创建时间',
                                      auto_now_add=True,
                                      # default=now,
                                      blank=True, null=True)
    changetime = models.DateTimeField('修改时间', auto_now=True, blank=True, null=True)
    agenttime = models.DateTimeField('配置更新', blank=True, null=True, help_text='最近一次主机客户端自动脚本运行更新软硬件信息的时间')

    usergroup = models.ManyToManyField(Group, verbose_name='网站用户组', blank=True, help_text='网站哪些用户组能对当前主机进行操作')
    user = models.ManyToManyField(User, verbose_name='网站用户权限', blank=True,
                                  # through='Host_User',  # 行级别的权限控制，人工录入时麻烦，比较困难实现快速批量设置主机清单
                                  help_text='网站哪些用户能对当前主机进行操作，超级用户直接有操作权限')
    ssh_user = models.ForeignKey(SshUser, verbose_name='SSH终端用户', on_delete=models.SET_NULL, null=True, blank=True, help_text='当前主机的SSH用户，用于ssh连接执行命令或终端WEB SSH')

    buydate = models.DateField('购买日期', default=datetime.today, blank=True, null=True)
    position = models.CharField(u"所处位置", max_length=250, default='', null=True, blank=True)
    sernumb = models.CharField(u"服务编号", max_length=150, default='', null=True, blank=True)
    sercode = models.CharField(u"服务代码", max_length=150, default='', null=True, blank=True)
    admin = models.ForeignKey(User, verbose_name='管理人', related_name='user_set2', null=True, blank=True, help_text='负责人直接有(当前主机/名下主机)操作权限')

    tomcat = models.CharField(max_length=100, verbose_name=u"Tomcat目录", default='/data/app/tomcat')
    tomcat_ver = models.CharField(max_length=50, verbose_name=u"Tomcat版本", default='', blank=True)
    jdk_ver = models.CharField(max_length=50, verbose_name=u"JDK版本", default='', blank=True)
    kernel = models.CharField(max_length=60, verbose_name=u"系统内核版本", default='', blank=True)

    # idc = models.ForeignKey(Idc, verbose_name=u"所在机房", on_delete=models.SET_NULL, null=True, blank=True)
    # position = models.CharField(u"所在位置", max_length=100, null=True, blank=True)
    # info = models.CharField(u"应用信息", max_length=200, default='', null=True, blank=True)
    text = models.TextField(u"备注信息", default='', null=True, blank=True)

    class Meta:
        permissions = (
            # 实现表级别的权限控制
            ("deploy_host", "Can deploy host"),    # APP部署
            ("webssh_host", "Can webssh host"),    # 终端登陆
            ("grep_host", "Can grep host"),      # 执行日志搜索
            ("run_sh_host", "Can run_sh host"),    # 执行常用命令
            ("run_cmd_host", "Can run_cmd host"),   # 执行自定义命令
            ("other_do_host", "Can other_do host"),  # 执行其它操作，如ES节点索引
        )
        ordering = ['group', 'ip']
        verbose_name = '主机'

    def __unicode__(self):
        return '%s - %s' % (self.name, self.ip)

    @staticmethod
    def newhost(kwargs):
        # 添加/修改host数据
        hostname = kwargs['hostname']
        host = Host.objects.filter(hostname=hostname)
        try:
            if host:
                host = host[0]
                # print '已有记录',hostname,'更新主机信息'
                kwargs.pop('hostname')
                text = kwargs.get('text', '')
                if text:
                    kwargs['text'] = '%s\r\n%s' % (host.text, text)  # 备注信息只在原基础信息上追加
                for k, v in kwargs.items():
                    setattr(host, k, v)
                host.agenttime = datetime.today()
                host.save()
            else:
                # 添加新主机
                hostname, ip = kwargs.get('hostname', ''), kwargs.get('ip', '')
                kwargs['name'] = kwargs.get('name', '%s' % (hostname, ))  # 当标识名未提供，则填入计算机名。
                kwargs['asset_type'] = kwargs.get('asset_type', 2)  # 默认为虚拟机类型
                kwargs['agenttime'] = datetime.today()  # 配制更新日期

                group_id = kwargs.get('group_id', HostGroup.get_group(ip))

                if group_id:
                    kwargs['group_id'] = group_id

                Host(**kwargs).save()
            return 1
        except:
            print(traceback.format_exc())
            return 0

    def get_ssh_user(self):

cmdb/forms.py
# coding=utf-8
from django import forms
# from django.forms import ModelForm
from cmdb.models import Host, SshUser
from django.forms.widgets import CheckboxSelectMultiple

# from django.contrib.auth.models import User, Group


class HostForm(forms.ModelForm):
    # 前端主机添加页面

    class Meta:
        model = Host
        fields = '__all__'
        # exclude = ("asset_type",)

        widgets = {
            'user': CheckboxSelectMultiple,
            'usergroup': CheckboxSelectMultiple,
        }

        # error_messages = {
        #     'model':{
        #         'max_length': ('太短了'),
        #     }
        # }

        # help_texts = {
        #     'user': u'哪些登陆用户能对当前主机进行操作，超级用户直接有操作权限'
        # }

    # model_field = Meta.model._meta.get_field('user')
    # user = forms.ModelMultipleChoiceField(widget=CheckboxSelectMultiple, queryset=User.objects.filter(is_superuser=False), label=model_field.verbose_name, required=False, help_text=model_field.help_text)


class HostForm2(HostForm):
    # 前端主机编辑页面去除 主机类型 字段

    class Meta(HostForm.Meta):
        exclude = ('asset_type', )


class SshUserForm(forms.ModelForm):
    # password = forms.CharFie()ld(label=u"密码", widget=forms.PasswordInput, required=False)

    class Meta:
        model = SshUser
        fields = '__all__'
        # exclude = ("id",)

        widgets = {
            'password': forms.PasswordInput(),
        }

        labels = {

        }

        help_texts = {
        }
        error_messages = {

        }

webssh/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


def index(request):
    # import ipdb;ipdb.set_trace()
    return render(request, 'index.html')

cmdb/templates/host_1.html
{% extends "_base.html" %}
{% load bootstrap3 %}

{% block  title %}主机信息{% endblock %}


{% block page-content %}

    {% block host-head %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                <li>
                    <a href="{% url 'cmdb:host' %}?t=1">物理机管理</a>
                </li>
                <li class="active">
                    <strong>物理机信息</strong>
                </li>
                <li>
                    <a href="{% url 'cmdb:host' %}?m={{ id }}">查看下属主机列表</a>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    {% endblock host-head %}


    <div class="row wrapper wrapper-content animated fadeInRight">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>信息更新</h5>

                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" class="form-horizontal"
                          action=""
                          method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="ref_url" value="{{ ref_url }}">
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}
                        <div class="form-group">

                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本信息</h3>
                                {% bootstrap_field form.name layout="horizontal" %}
                                {% bootstrap_field form.hostname layout="horizontal" %}
                                {% bootstrap_field form.ip layout="horizontal" %}
                                {% bootstrap_field form.other_ip layout="horizontal" %}
                                {% bootstrap_field form.group layout="horizontal" %}
                                {% bootstrap_field form.usergroup layout="horizontal" %}
                                {% bootstrap_field form.user layout="horizontal" %}
                                {% bootstrap_field form.tomcat layout="horizontal" %}
                                {% bootstrap_field form.tomcat_ver layout="horizontal" %}
                                {% bootstrap_field form.jdk_ver layout="horizontal" %}
                                {#% bootstrap_field form.app layout="horizontal" %#}

                                {% bootstrap_field form.text layout="horizontal" %}

                                {% block host-info1 %}
                                <div class="form-group">
                                    <label class="col-md-3 control-label">所含虚拟主机</label>
                                    <div class="col-md-9"><div id="id_host">

                                    {% for host in hosts_off %}
                                    <div class="checkbox"><label><input type="checkbox" name="host" value="{{ host.id }}"> {{ host }}</label></div>
                                    {% endfor %}

                                    {% if hosts_off and hosts_on %}<div class=""><label>------------------------</label></div>{% endif %}

                                    {% for host in hosts_on %}
                                    <div class="checkbox"><label><input type="checkbox" name="host" value="{{ host.id }}" checked > {{ host }}</label></div>
                                    {% endfor %}


                                    </div></div>
                                </div>
                                {% endblock host-info1 %}

                            </div>
                        </div>


                        {% block host-info2 %}
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                               <h3>业务信息</h3>
                                {% bootstrap_field form.status layout="horizontal" %}

                                {% bootstrap_field form.buydate layout="horizontal" %}

                                {% bootstrap_field form.position layout="horizontal" %}
                                {% bootstrap_field form.sernumb layout="horizontal" %}
                                {% bootstrap_field form.sercode layout="horizontal" %}
                                {% bootstrap_field form.admin layout="horizontal" %}

                            </div>
                        </div>
                        {% endblock host-info2 %}



                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                               <h3>软硬件信息</h3>
                                {% bootstrap_field form.os layout="horizontal" %}
                                {% bootstrap_field form.kernel layout="horizontal" %}
                                {% bootstrap_field form.cpu_model layout="horizontal" %}
                                {% bootstrap_field form.cpu_num layout="horizontal" %}

                                {% bootstrap_field form.memory layout="horizontal" %}
                                {% bootstrap_field form.disk layout="horizontal" %}
                                {% bootstrap_field form.vendor layout="horizontal" %}
                                {% bootstrap_field form.sn layout="horizontal" %}

                                {% block host-info3 %}
                                {% endblock host-info3 %}


                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                <button class="btn btn-primary" type="submit">提交</button>
                                <button class="btn btn-white" type="reset">重置</button>
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>

{% endblock %}


{% block footer-js %}
        <script>
            $(document).ready(function () {
                $('.select2').select2();
            })
        </script>


{% endblock %}






cmdb/templates/hostlist_2.html
{% extends "_base.html" %}


{% block  title %}资产信息{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产管理</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/">主页</a>
                </li>
                {% if parent_name %}
                <li class="active">
                    <strong>({{ parent_name }}) 下属主机列表</strong>
                </li>
                <li>
                    <a href='javascript:history.go(-1)'>返回上一层</a>
                </li>
                {% else %}
                <li>
                    虚拟机管理
                </li>
                <li class="active">
                    <strong>虚拟机列表</strong>
                </li>
                {% endif %}
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>资产信息</h5>

                    </div>
                    <div class="ibox-content">

                          <div class="table-responsive">
                            {% if not parent_name %}
                            <a href="{% url 'cmdb:host_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <a class="btn btn-danger" data-toggle="modal"
                               data-target="#myModal2">批量删除
                            </a>
                            <a class="btn btn-info" onclick="javascript:run_cmd3()">批量更新配置
                            </a>
                            <form id="cmd3" action="{% url 'cmdb:cmdrun' %}" method="post" target="_blank">{% csrf_token %}<input type="hidden" name="hosts"/><input type="hidden" name="cmd"/></form>
                            {% endif %}




                            <form id="form_asset_all" class="form-horizontal  ">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th width="120">名称</th>
                                        <th>主机名</th>
                                        <th>管理IP</th>
                                        <th>tomcat版本</th>
                                        <th>JDK版本</th>
                                        <th>系统版本</th>
                                        <th>配置更新</th>
                                        <th>动作</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   hosts %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}"  name="id"></td>
                                            <td class="center"><a
                                                    href="{% url 'cmdb:host' %}/{{ row.id }}/">{{ row.name }}</a>
                                            </td>
                                            <td>{{ row.hostname }}</td>
                                            <td>{{ row.ip }}</td>
                                            <td>{{ row.tomcat_ver }}</td>
                                            <td>{{ row.jdk_ver }}</td>
                                            <td>{{ row.os }}</td>
                                            <td>{{ row.agenttime }}</td>
                                            <td>
                                                <a class="btn btn-primary  btn-xs " href="/admin/cmdb/host/{{ row.id }}/change/" target="_blank">详情</a>
                                                <a class="btn btn-xs btn-success " href="{% url  'cmdb:webssh' %}#hostid_{{ row.id }}" title="WebSSH" target="_blank">终端</a>
                                                {% if not parent_name %}
                                                <a class="btn btn-xs btn-info" title="更新主机配置" onclick="javascript:run_cmd3(this)">更新</a>
                                                <a class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal1" onclick="javascript:del_host(this)">删除 </a>
                                                {% endif %}


                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal inmodal" id="myModal1" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">删除</h4>
                    <span id="error" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="asset_del_form">
                    <div class="modal-body">

                        <div class="form-group"><input type="text" name="nid" style="display:none"/></div>
                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm asset_del">删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <div class="modal inmodal" id="myModal2" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">批量删除</h4>
                    <span id="error_all" style="color:red;"></span>
                    <small></small>
                </div>
                <form id="del_form">
                    <div class="modal-body">

                        <p><strong>确定删除？</strong></p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                        <a class="btn btn-danger m-r-sm  asset_all_del"> 批量删除</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

{% block footer-js %}


        <script>

            function run_cmd3(obj=null){
                // 执行自定义命令，更新客户端机器配置信息
                if (obj) {
                    // 更新单台主机配置
                    var host_ids = $(obj).parent().parent().attr('id');
                }
                else {
                    var host_ids = '';
                    var cs=document.getElementsByName('id');
                    for (i=0; i < cs.length; i++) {
                        if (cs[i].checked) {
                            host_ids = host_ids+cs[i].value+',';
                            // console.log(cs[i].value);
                        }
                    }
                }

                var cmd3_form = $("#cmd3")[0];
                cmd3_form.hosts.value = host_ids;
                var url = window.location.host;
                cmd3_form.cmd.value = "wget -t1 -T5 -O agent.py http://"+url+"/static/agent.py >& /dev/null && python agent.py";

                // 提交自定义命令
                cmd3_form.submit();

            }
            function del_host(obj){
                var id = $(obj).parent().parent().attr('id');
                $('#asset_del_form').find('input[name="nid"]').val(id);
            }
            $(function () {

                $('.asset_del').click(function () {
                    $.ajax({
                        url: "/cmdb/host/del",
                        type: 'POST',
                        data: $('#asset_del_form').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.reload()
                            } else {
                                $('#error').text(obj.error);
                            }
                        }
                    })
                });

                $('.asset_all_del').click(function () {
                    var chk_value =[];
                    $('input[name="id"]:checked').each(function(){ 
                        chk_value.push($(this).val()); 
                    });
                    if (chk_value.length==0) {
                        // alert("未选择任何主机，操作已忽略");
                        // $('#error_all').text("未选择任何主机..");
                        return
                    }
                    $.ajax({
                        url: "/cmdb/host/alldel",
                        type: 'POST',
                        data: $('#form_asset_all').serialize(),
                        success: function (data) {
                            var obj = JSON.parse(data);
                            if (obj.status) {
                                location.reload()
                            } else {
                                $('#error_all').text(obj.error);
                            }
                        }

                    })
                });


            });


        </script>

{% endblock %}